#!/bin/fish

function show_help
    echo -e "Transform MAIS XML into well-formed XML\n"
    echo -e (set_color -o --underline)"Usage:"(set_color normal -o) \
        "fixmaisxml"(set_color normal)" FILE.xml [FILE2.xml ...]\n"

    echo (set_color -o --underline)"Options:"(set_color normal)
    echo -e -- '  --defix, -d\tDetransform ("defix") well-formed XML into MAIS XML'
end

if test (count $argv) -eq 0
    show_help
    exit 1
end

if contains -- -h $argv; or contains -- --help $argv
    show_help
    exit 0
end

if string match -qr -- "--defix" "$argv[1]$argv[-1]"; or string match -qr -- "-d" "$argv[1]$argv[-1]"
    for f in $argv[2..]
        sd '</MFEXPORT>' '' $f
        sd -A -f ms '<!\[CDATA\[(.*?)\]\]>' '$1' $f
    end
    exit 0
end

# regex for tags whose contents need to be wrapped in CDATA
set cdata_tags (string join "|" WAARDE CODE REL_CODE REL_TOP_CODE TREFWOORD OMSCHRIJVING NAAM BESCHR?IJVING PADNAAM PROMPT)

for f in $argv
    # add some idempotency by checking if closing tag has already been inserted
    if tail $f | grep -q '</MFEXPORT>'
        echo "Skipping $f, since it seems to be fixed already"
        continue
    end

    # certain elems can hold any data, including malformed HTML/XML. Hence, we
    # wrap their contents in a CDATA section
    sd "<($cdata_tags)>" '$0<![CDATA[' $f
    sd "</($cdata_tags)>" ']]>$0' $f

    # control characters arent valid xml so we replace them with nothing: ''
    sd '[\x00-\x08\x0B\x0C\x0E-\x1F\u{FFFE}\u{FFFF}]' '' $f

    # root-elem <MFEXPORT> lacks a closing tag, so append it
    printf '</MFEXPORT>' >> $f
end
