#!/bin/fish

function show_help
    echo -e "Transform MAIS XML into well-formed XML\n"
    echo (set_color -o --underline)"Usage:"(set_color normal -o) \
        "fixmaisxml"(set_color normal)" FILE.xml [FILE2.xml ...]"
end

if test (count $argv) -eq 0
    show_help
    exit 1
end

if contains -- -h $argv; or contains -- --help $argv
    show_help
    exit 0
end

# regex for tags whose contents need to be wrapped in CDATA
set cdata_tags (string join "|" WAARDE CODE REL_CODE REL_TOP_CODE TREFWOORD OMSCHRIJVING NAAM BESCHRIJVING PADNAAM PROMPT)

for f in $argv
    # add some idempotency by checking if closing tag has already been inserted
    if tail $f | grep -q '</MFEXPORT>'
        echo "Skipping $f, since it seems to be fixed already"
        continue
    end

    # certain elems can hold any data, including malformed HTML/XML. Hence, we
    # wrap their contents in a CDATA section
    sd "<($cdata_tags)>" '$0<![CDATA[' $f
    sd "</($cdata_tags)>" ']]>$0' $f

    # ampersands seem to never be inserted correctly
    # FIXME: is &amp; truly never used?
    sd '&' '&amp;' $f

    # control characters arent valid xml so we replace them with nothing: ''
    sd '[\x00-\x08\x0B\x0C\x0E-\x1F\u{FFFE}\u{FFFF}]' '' $f

    # root-elem <MFEXPORT> lacks a closing tag, so append it
    printf '</MFEXPORT>' >> $f
end
